### ISSUE TITLE
Crash on world creation

### ISSUE THREAD

**Issue by ModifiedMC** [Octo-Studios/perception#1] opened 2024-12-20 05:59 UTC
Neoforge v  21.1.90
Perception v 0.1-1.21.1
Octolib v 0.5

Used in combination with several mods, tried without connector & the fabric mods and the issue still persists.

[Crash report](https://mclo.gs/mVan9k5)

**Comment by IMS212** [comment] 2024-12-21 19:07
Caused by Visuality. Visuality seems to intentionally create a particle with broken particle data, which is then caught by a Mixin they have in ParticleEngine; but Perception has no such check, and crashes trying to look up a null key.

**Comment by SSKirillSS** [comment] 2024-12-22 11:06
Thanks for the info. Should be fixed since 0.1.0.1.

**Closed by SSKirillSS** 2024-12-22 11:06 UTC
